routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::controller(\App\Http\Controllers\PageController::class)
    ->name('page.')->group(function () {
        Route::get('/','index')->name('index');
        Route::get('/contact-us','contactUs')->name('contact');
        Route::get('/about-us','aboutUs')->name('about');
        Route::get('/sitemap.xml','sitemap')->name('sitemaps');
        Route::get('/sitemap.xml/articles','sitemap')->name('sitemap');
    });

Route::controller(\App\Http\Controllers\BlogController::class)
    ->name('blog.')->group(function () {
        Route::get('/articles','index')->name('articles');
        Route::get('/{slug}','single')->name('detail');
    });

resources/views/about-us.blade.php
@extends('layouts.master')
@section('title', 'درباره ما')
@section('description', '')
@section('content')
    @include('layouts.header', [
        'title' => 'درباره ما',
        'description' => 'هر چیزی که لازم است درباره ما بدانید',
        'background' => 'assets/img/about-bg.jpg',
    ])

    <main class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {!! setting('about_us', 'توضیحات درباره ما') !!}
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/contact-us.blade.php
@extends('layouts.master')
@section('title', 'تماس با ما')
@section('description', '')
@section('content')
    @include('layouts.header', [
        'title' => 'تماس با ما',
        'description' => 'به راحتی میتوانید به ما تماس بگیرید',
        'background' => 'assets/img/contact-bg.jpg',
    ])
    <!-- Main Content-->
    <main class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <p>در صورت داشتن هرگونه سوال میتوانید ار فرم زیر با ما ارتباط بگیرین</p>
                    <div class="my-5">
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- * * SB Forms Contact Form * *-->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- This form is pre-integrated with SB Forms.-->
                        <!-- To make this form functional, sign up at-->
                        <!-- https://startbootstrap.com/solution/contact-forms-->
                        <!-- to get an API token!-->
                        <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                            <div class="form-floating">
                                <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                <label for="name">نام</label>
                                <div class="invalid-feedback" data-sb-feedback="name:required">نام اجباری است</div>
                            </div>
                            <div class="form-floating">
                                <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                                <label for="email">ایمیل</label>
                                <div class="invalid-feedback" data-sb-feedback="email:required">ایمیل اجباری است</div>
                                <div class="invalid-feedback" data-sb-feedback="email:email">ایمیل نادرست است</div>
                            </div>
                            <div class="form-floating">
                                <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                                <label for="phone">شماره تماس</label>
                                <div class="invalid-feedback" data-sb-feedback="phone:required">یک شماره تماس وارد کنید</div>
                            </div>
                            <div class="form-floating">
                                <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                                <label for="message">متن پیام</label>
                                <div class="invalid-feedback" data-sb-feedback="message:required">متن پیام اجباری است</div>
                            </div>
                            <br />
                            <!-- Submit success message-->
                            <!---->
                            <!-- This is what your users will see when the form-->
                            <!-- has successfully submitted-->
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">فرم تماس با موفقیت ثبت شد</div>
                                    To activate this form, sign up at
                                    <br />
                                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                </div>
                            </div>
                            <!-- Submit error message-->
                            <!---->
                            <!-- This is what your users will see when there is-->
                            <!-- an error submitting the form-->
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">خطای در ارسال ره داده است</div></div>
                            <!-- Submit Button-->
                            <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">ارسال</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/index.blade.php
@extends('layouts.master')
@section('title', 'صفحه اصلی')
@section('description', setting('site_description', 'توضیحات سایت نانو بلاگ'))
@section('content')
    @php
        $author = setting('site_author', 'مدیر سایت');
    @endphp
    @include('layouts.header', [
        'title' => setting('site_name', 'نانو بلاگ'),
        'description' => setting('site_description', 'توضیحات سایت نانو بلاگ'),
        'background' => 'assets/img/home-bg.jpg',
    ])
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                @foreach($posts as $post)
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{{route('blog.detail',['slug' => $post->slug])}}">
                        <h2 class="post-title">{{$post->title}}</h2>
                        <h3 class="post-subtitle">{{$post->short()}}</h3>
                    </a>
                    <p class="post-meta">
                        توسط
                        <a href="{{url('/')}}">{{$post->author ?? $author}}</a>
                        در {{jdate($post->created_at)->format('j F Y')}}
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
                @endforeach
                <!-- Pager-->
                <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{{route('blog.articles')}}">نمایش بیشتر →</a></div>
            </div>
        </div>
    </div>
@endsection

resources/views/sitemap.blade.php
<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    @foreach ($posts as $post)
        <url>
            <loc>{{ url('/') }}/{{ $post->slug }}</loc>
            <lastmod>{{ $post->created_at->tz('UTC')->toAtomString() }}</lastmod>
            <changefreq>daily</changefreq>
        </url>
    @endforeach
</urlset>

resources/views/sitemaps.blade.php
<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>

<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    @for($i=1;$i<$lastPage;$i++)
        <sitemap>
            <loc>{{url('/')}}/sitemap.xml/articles?page={{$i}}</loc>
        </sitemap>
    @endfor
</sitemapindex>